Parameters:
  S3Backend:
    Type: String
  S3Frontend:
    Type: String

Resources:
  S3BucketBackend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3Backend
      MetricsConfigurations:
        - Id: EntireBucket
  S3BucketFrontend:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref S3Frontend
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        RoutingRules:
          - RedirectRule:
              ReplaceKeyWith: 'index.html'
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: '404'
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3BucketFrontend
                - /*
      Bucket: !Ref S3BucketFrontend
Outputs:
  WebsiteURL:
    Value: !GetAtt [S3BucketFrontend, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3BucketFrontend, DomainName]]]
    Description: Name of S3 bucket to hold website content
